#  _____     _        _             #
# |  __ \   | |      (_)            #
# | |__) |__| |_ _ __ _  ___ _   _  #
# |  ___/ _ \ __| '__| |/ __| | | | #
# | |  |  __/ |_| |  | | (__| |_| | #
# |_|   \___|\__|_|  |_|\___|\__,_| #
#                                   #

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[✗](bold red)'

[battery]
format = ' [$symbol]($style)'

[[battery.display]]
threshold = 25
style = 'bold red'

[[battery.display]]
threshold = 50
style = 'bold orange'

[[battery.display]]
threshold = 75
style = 'bold yellow'

[[battery.display]]
threshold = 100
style = 'bold green'

[memory_usage]
disabled = false
threshold = -1
symbol = ' '
style = 'bold dimmed green'
format=' [$ram]($style) '

[shell]
zsh_indicator = '%'
bash_indicator = '\$'
powershell_indicator = '_'
fish_indicator = ''
disabled = false

[username]
show_always = true
style_root = 'bold red'
style_user = 'bold cyan'
format = " [$user]($style) in " 
