#! /bin/bash

pgrep -x sxhkd >/dev/null || sxhkd &

MONITORS=$(xrandr --query | grep -w connected | awk '{print $1}' | wc -l)

if [[ $MONITORS -eq 3 ]]; then
	# Set display from arandr saved script
	sh ~/.screenlayout/monitor.sh &

	bspc monitor DP3 -d I II III IV
	bspc monitor eDP1 -d V VI VII VIII
	bspc monitor DP1 -d IX X
else
	bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width 2
bspc config window_gap 10

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

# bspc rule -a firefox desktop='^2' # note to self: uncomment this once you figure multi-monitors in bspwm+polybar
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a jetbrains-toolbox state=floating

# Border
bspc config focused_border_color "#81a1c1"
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#073642"

#
# Autostart
#
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
$HOME/.fehbg &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/
# Picom
picom -CGb &
# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# hack needed for Jebrains IDEs to work
wmname LG3D &

# start redshift
redshift &
